"""
Auto-generated ML Pipeline
--------------------------
Generated by AutoML Pipeline Builder

You can modify:
- DATASET_PATH
- TARGET_COLUMN
- MODEL_TYPE
- Retrain with new data
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, r2_score
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import joblib

# =============================
# CONFIGURATION
# =============================

DATASET_PATH = "uploads/loan_default.csv"
TARGET_COLUMN = "default"
PROBLEM_TYPE = "classification"
SELECTED_MODEL = "LogisticRegression"

# =============================
# LOAD DATA
# =============================

df = pd.read_csv(DATASET_PATH)
X = df.drop(columns=[TARGET_COLUMN])
y = df[TARGET_COLUMN]

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =============================
# BUILD MODEL
# =============================

if PROBLEM_TYPE == "classification":
    if SELECTED_MODEL == "LogisticRegression":
        model = LogisticRegression(max_iter=1000)
    else:
        model = RandomForestClassifier()

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

else:
    if SELECTED_MODEL == "LinearRegression":
        model = LinearRegression()
    else:
        model = RandomForestRegressor()

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

# =============================
# TRAIN
# =============================

pipeline.fit(X_train, y_train)

# =============================
# EVALUATE
# =============================

preds = pipeline.predict(X_test)

if PROBLEM_TYPE == "classification":
    metric = accuracy_score(y_test, preds)
    print(f"Accuracy: 1.0000")
else:
    metric = r2_score(y_test, preds)
    print(f"R2 Score: 1.0000")

# =============================
# SAVE MODEL
# =============================

joblib.dump(pipeline, "trained_pipeline.joblib")
print("Saved trained_pipeline.joblib")